#!/bin/bash

set -e

if [ ! -e REQUIRE ]
then
	julia $*
	exit
fi

HASH=`nix-hash REQUIRE`

export JULIA_PKGDIR=$HOME/.julia/juliawithpackages/$HASH
export JULIA_LOAD_PATH="`pwd`/modules"

if [ ! -e $JULIA_PKGDIR/v0.3/REQUIRE ] #&& [ ! -e $JULIA_PKGDIR/v0.4/REQUIRE ]
then
	julia INSTALLSCRIPT
fi

julia --no-startup $* 
	

